//
//  Workspace.swift
//  ProjectDescriptionHelpers
//
//  Created by Ari on 2024/11/11.
//

import ProjectDescription

let workspace = Workspace(
    name: "Animal-Crossing-Wiki",
    projects: [
        "Animal-Crossing-Wiki/Projects/ACNHCore",
        "Animal-Crossing-Wiki/Projects/ACNHShared",
        "Animal-Crossing-Wiki/Projects/App"
    ],
    generationOptions: .options(enableAutomaticXcodeSchemes: false, autogeneratedWorkspaceSchemes: .disabled)
)
